apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: config
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: demo-pod
        image: badmancarteer/practice-class:3
        ports:
        - containerPort: 80
        